name: Quarkiverse Pre Release

on:
  workflow_dispatch:

#  pull_request:
#    paths:
#      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    name: Pre-Release
    uses: xstefank/.github/.github/workflows/pre-release.yml@main
    secrets: inherit